### ISSUE TITLE
tls: oversized record received with length 28012

### ISSUE THREAD

**Issue by xor-gate** [xmppo/go-xmpp#82]
Hi,

We are running a prosody 0.9.12 with TLS enabled. I'm not sure why this error is raised (unknown ciphers maybe?):

```
2017/02/11 15:04:57 tls: oversized record received with length 28012
```

I'm not sure how I can debug this SSL/TLS communication.

**Comment by xor-gate** [comment]
Some tracing with openssl s_client:

```
jerry@iMac:~ > openssl version
OpenSSL 0.9.8zh 14 Jan 2016
jerry@iMac:~ > openssl s_client -connect domain:5222
CONNECTED(00000004)
47132:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.30.2/src/ssl/s23_clnt.c:618:
```

**Comment by xor-gate** [comment]
Probably this is due to STARTTLS:

```
jerry@iMac:~ > openssl s_client -connect domain:5222 -starttls xmpp
CONNECTED(00000004)
depth=0 /C=NL/L=The Netherlands/O=domain/OU=XMPP Department/CN=rikvdh.com/emailAddress=xmpp@domain
verify error:num=18:self signed certificate
verify return:1
depth=0 /C=NL/L=The Netherlands/O=domain/OU=XMPP Department/CN=domain.com/emailAddress=xmpp@domain
verify return:1
```

**Comment by xor-gate** [comment]
Probably related to #78

**Comment by mattn** [comment]
did you try InsecureSkipVerify ?

**Comment by xor-gate** [comment]
I have modified the `_example/example.go`:

```
 42         xmpp.DefaultConfig = tls.Config{
 43                 ServerName:         serverName(*server),
 44                 InsecureSkipVerify: true,
 45         }
```

Stil the same

**Comment by xor-gate** [comment]
Seems there is more going on with this: http://stackoverflow.com/questions/36073179/tls-oversized-record-received-with-length-xxxxx

**Comment by cooox** [comment]
@xor-gate I got the same setup and the same error, the solution is to disable TLS and enable StartTLS in Options. Here's an extract from my code that does the full XMPP routine:

```go
func sendXMPP(message string) {
    options := xmpp.Options{
        Host: "real_xmppserver_address:5222",
        User: "user@jabber_domain",
        Password: "password",
        NoTLS: true,
        StartTLS: true,
        TLSConfig: &tls.Config{
            ServerName: "jabber_domain",
            InsecureSkipVerify: false,
        },
        Debug: true,
        Session: false,
        Status: "xa",
        StatusMessage: "Hello! I'm using XMPP",
    }

    client, err := options.NewClient()
    if err != nil {
        log.Fatal(err)
    }

    log.Println(client.Roster())

    client.Send(xmpp.Chat{
        Remote: "jid_of_receiver",
        Type: "chat",
        Text: message,
    })
}
```

It's in the docs as well, somewhat hidden 😉 

```
// NoTLS directs go-xmpp to not use TLS initially to contact the server; instead, a plain old unencrypted
// TCP connection should be used. (Can be combined with StartTLS to support STARTTLS-based servers.)
NoTLS bool

// StartTLS directs go-xmpp to STARTTLS if the server supports it; go-xmpp will automatically STARTTLS
// if the server requires it regardless of this option.
StartTLS bool
```
and in fact it's enough to set `NoTLS: true`, which leads `Client.startTLSIfRequired()` to initiate an encrypted StartTLS session. (I verified this with Wireshark)

**Comment by Fank** [comment]
Same issue here `2017/10/02 16:25:22 tls: oversized record received with length 29285`
Server is Openfire 4.1.5 with letsencrypt certificates

**Comment by Jeorch** [comment]
There is still no good solution for `tls: oversized record received with length 29285`

**Comment by Jeorch** [comment]
I solved my problem. This `tls: oversized record received with length 29285` is because of a problem with my openfire configuration. I changed the setting of openfire's STARTTLS to optional.Then set "InsecureSkipVerify, NoTLS, StartTSL" to true.
`
xmpp.DefaultConfig = tls.Config{
   ServerName:         serverName(*server),
   InsecureSkipVerify: true,
}

options := xmpp.Options{Host: *server,
   User:          *username,
   Password:      *password,
   NoTLS:         true,
   StartTLS:      true,
   Debug:         *debug,
   Session:       *session,
   Status:        *status,
   StatusMessage: *statusMessage,
}
`
I think when you have this problem, it's not necessarily your client Settings that have the problem, it's probably your server.

**Comment by Jeorch** [comment]
I solved my problem. This tls: oversized record received with length 29285 is because of a problem with my openfire configuration. I changed the setting of openfire's STARTTLS to optional.Then set "InsecureSkipVerify, NoTLS, StartTSL" to true.
```
xmpp.DefaultConfig = tls.Config{
ServerName: serverName(*server),
InsecureSkipVerify: true,
}

options := xmpp.Options{Host: *server,
User: *username,
Password: *password,
NoTLS: true,
StartTLS: true,
Debug: *debug,
Session: *session,
Status: *status,
StatusMessage: *statusMessage,
}
```
I think when you have this problem, it's not necessarily your client Settings that have the problem, it's probably your server.

**Comment by mdosch** [comment]
I am closing this issue as this seems to be a server issue.
